# -*- coding: utf-8 -*-
"""
Localization module for Screen OCR + TTS.

This module is responsible ONLY for user-facing texts (English + Russian).
The GUI module (gui.py) stays fully in English and pulls every visible
string from here through the tr() helper.

Usage:
    from localization import tr, set_language
    set_language("en")          # or "ru"
    label = tr("btn_scan_all")  # -> "Scan All (F9)" / "Сканировать все (F9)"
"""

_current_lang = "en"


def set_language(lang: str) -> None:
    """Set the active UI language ('en' or 'ru')."""
    global _current_lang
    if lang in TEXTS:
        _current_lang = lang


def get_language() -> str:
    """Return the active UI language code."""
    return _current_lang


def tr(key: str, **kwargs) -> str:
    """Translate a key to the active language with English/key fallback."""
    table = TEXTS.get(_current_lang, {})
    text = table.get(key)
    if text is None:
        text = TEXTS["en"].get(key, key)
    if kwargs:
        try:
            text = text.format(**kwargs)
        except (KeyError, IndexError):
            pass
    return text


# Multi-voice role names (must match keys in voice_profiles.py defaults).
ROLE_HEROINE = "Героиня"
ROLE_HERO = "Герой"


TEXTS = {
    "en": {
        # --- Window / tabs ---
        "app_title": "Screen OCR + TTS",
        "tab_regions": "Regions",
        "tab_scan": "Scan",
        "tab_result": "Result",
        "tab_tts": "TTS",
        "tab_logs": "Logs",
        "tab_settings": "⚙ Settings",
        "tab_voice_profiles": "Voice Profiles",
        "tab_web_live": "Web Live",
        "tab_translator": "Translator",
        "offline_tab_info": "Offline: EasyOCR + TTS without internet",
        "online_tab_info": "Online: Edge-TTS + Translator + Web server",
        "combined_tab_info": "All voices: Edge (online) + RHVoice/Silero/SAPI5 (offline)",
        # --- File manager nav ---
        "cat_main": "Home",
        "cat_voice": "Voice",
        "cat_translate": "Translator",
        "cat_web": "Web Server",
        "cat_settings": "Settings",
        "cat_logs": "Logs",
        "search_placeholder": "Search...",
        "view_grid": "Grid",
        "view_list": "List",
        "sort_label": "Sort:",
        "sort_importance": "By importance",
        "sort_name": "By name",
        "sort_recent": "Recent",
        # --- Status bar ---
        "status_ready": "Ready | Ctrl+drag — create a frame",
        "live_off_label": "Live: OFF",
        "live_on_label": "Live: ON",
        "btn_to_tray": "▽ To tray",
        # --- Region dialog ---
        "color_green": "Green",
        "color_blue": "Blue",
        "color_orange": "Orange",
        "color_purple": "Purple",
        "color_red": "Red",
        "color_cyan": "Cyan",
        "color_yellow": "Yellow",
        "color_white": "White",
        "color_black": "Black",
        "color_pink": "Pink",
        "shape_rect": "Rectangle",
        "shape_circle": "Circle",
        "shape_ellipse": "Ellipse",
        "dlg_region_props": "Region properties",
        "lbl_name": "Name:",
        "lbl_width": "W:",
        "lbl_height": "H:",
        "lbl_frame_color": "Frame color:",
        "lbl_frame_shape": "Frame shape:",
        "chk_click_through": "Click-through (no mouse/keyboard capture)",
        "tip_click_through": "When enabled the frame does not intercept clicks and keyboard input",
        "lbl_tts_voice": "TTS voice:",
        "region_default_name": "R{x}",
        # --- Regions tab ---
        "regions_hint": "Ctrl+drag to create frame",
        "regions_list_group": "Region list",
        "btn_edit_mode_on": "Edit mode: ON",
        "btn_edit_mode_off": "Edit mode: OFF",
        "btn_add": "Add",
        "btn_edit": "Edit",
        "btn_delete": "Delete",
        # --- Scan tab ---
        "ocr_settings_group": "OCR settings",
        "lbl_language": "Language:",
        "lbl_engine": "Engine:",
        "lbl_content_preset": "Content preset:",
        "live_mode_group": "Live Mode",
        "chk_enable_live": "Enable Live Mode",
        "lbl_interval": "Interval:",
        "suffix_ms": " ms",
        "chk_detect_changes": "Detect changes",
        "scan_mode_group": "Scan Mode",
        "lbl_scan_mode": "Mode:",
        "scan_mode_normal": "Normal (on demand)",
        "scan_mode_realtime_clear": "Realtime (clear previous)",
        "scan_mode_realtime_keep": "Realtime (keep history)",
        "chk_separate_regions": "Separate result per region",
        "status_speech_started": "Speech mode {mode} started",
        "status_speech_stopped": "Speech mode {mode} stopped",
        "speech_modes_group": "Speech Modes (hotkeys 1-4)",
        "speech_mode_1": "1: Single voice",
        "speech_mode_2": "2: Multi-voice",
        "speech_mode_3": "3: Realtime single",
        "speech_mode_4": "4: Realtime by roles",
        "speech_mode_none": "Speech: OFF",
        "speech_mode_active": "Speech: mode {mode} ACTIVE",
        "chk_web_tts": "Web TTS server (SAPI)",
        "status_web_tts_on": "Web TTS server started on port {port}",
        "status_web_tts_off": "Web TTS server stopped",
        "tab_web_live": "Live TTS (Web)",
        "web_live_hint": "Озвучка голосом браузера (Алиса в Яндекс.Браузере)",
        "scan_group": "Scan",
        "btn_scan_selected": "Scan selected",
        "btn_scan_all": "Scan all",
        "live_tts_group": "Live TTS (continuous reading)",
        "btn_start_live_tts": "▶ Start Live TTS",
        "btn_stop_live_tts": "■ Stop (1)",
        "live_tts_idle": "Idle",
        "live_tts_active": "Active",
        "line_by_line_group": "Line-by-line mode",
        "chk_line_by_line": "Speak each line immediately",
        "tip_line_by_line": "Each new text line is spoken immediately, without waiting for the next scan",
        "line_by_line_active": "Active",
        "sync_group": "Voice sync",
        "chk_sync_mode": "Voice = priority (scan waits for speech)",
        "sentence_group": "Sentence-by-sentence",
        "chk_sentence_mode": "Read by sentences (text erases after reading)",
        # --- Result tab ---
        "result_group": "Recognized text (editable)",
        "btn_speak": "Speak",
        "btn_save_audio": "Save audio",
        "btn_save_txt": "Save .txt",
        "btn_copy": "Copy",
        "btn_clear": "Clear",
        "btn_stop_speaking": "Stop",
        "btn_instant_speak": "Instant",
        "btn_test_dialogue": "Test dialogue",
        "status_instant_speaking": "Instant speaking...",
        "status_multi_test": "Dialogue...",
        # --- TTS tab ---
        "voice_default_group": "Default voice",
        "lbl_voice": "Voice:",
        "speed_group": "Speed",
        "volume_group": "Volume",
        "playback_engine_group": "Playback engine",
        "engine_edge_playback": "edge-playback (fast, simple)",
        "engine_edge_vlc": "Edge-TTS → MP3 → VLC (streaming radio)",
        "engine_sapi": "Windows Speech API (offline)",
        "btn_save_mp3": "Save to MP3",
        "vlc_stream_group": "VLC streaming (radio)",
        "btn_start_stream": "▶ Start stream",
        "btn_stop_stream": "■ Stop stream",
        "btn_test_voice": "Test voice",
        "multi_voice_group": "Multi-voice",
        "chk_enable_multi_voice": "Enable multi-voice",
        "profiles_group": "Voice profiles",
        "voice_roles_group": "Voices for roles",
        "lbl_male_voice": "Male:",
        "lbl_female_voice": "Female:",
        "lbl_narrator": "Narrator:",
        "voice_settings": "Settings",
        "lbl_speed": "Speed:",
        "lbl_pitch": "Pitch:",
        "btn_test_this_voice": "Test this voice",
        "profile_name_ph": "Profile name...",
        "btn_save_profile": "Save",
        "btn_load_profile": "Load",
        "btn_del_profile": "Delete",
        "lbl_heroine": "Heroine:",
        "lbl_hero": "Hero:",
        "btn_apply_profiles": "Apply profiles",
        "btn_test_multi": "Test multi-voice",
        "multi_voice_hint": "Format: Name: text (e.g. Hello!)",
        # --- Logs tab ---
        "btn_refresh": "Refresh",
        "chk_auto_refresh": "Auto-refresh (5 s)",
        "btn_clear_logs": "Clear log",
        # --- Settings tab ---
        "settings_ocr_group": "OCR settings",
        "chk_use_gpu": "Use GPU (CUDA)",
        "lbl_confidence": "Confidence threshold:",
        "lbl_scan_interval": "Scan interval:",
        "chk_detect_changes_detect": "Detect frame changes",
        "lbl_change_threshold": "Change sensitivity:",
        "chk_auto_detect_region": "Auto-detect text region",
        "settings_tts_group": "TTS settings",
        "lbl_voice_type": "Voice type:",
        "chk_cache_audio": "Cache audio",
        "lbl_rate": "Speech rate:",
        "lbl_volume": "Volume:",
        "chk_multi_voice_mode": "Multi-voice (auto language detect)",
        "sapi_voices_loading": "SAPI voices: loading...",
        "sapi_voices_none": "No SAPI voices found",
        "sapi_voices_prefix": "SAPI: ",
        "settings_overlay_group": "Overlay / On-screen display",
        "chk_overlay_enabled": "Enable overlay",
        "chk_overlay_text": "Show recognized text on screen",
        "lbl_opacity": "Frame opacity:",
        "lbl_panel_opacity": "Panel opacity:",
        "lbl_overlay_font_size": "Font size:",
        "lbl_font_color": "Text color:",
        "lbl_bg_color": "Background color:",
        "lbl_position": "Position:",
        "settings_general_group": "General",
        "chk_start_minimized": "Start minimized to tray",
        "chk_log_enabled": "Enable logging to file",
        "lbl_log_level": "Log level:",
        "settings_web_tts_group": "Web TTS server",
        "lbl_web_tts_port": "Port:",
        "hotkeys_group": "Hotkeys",
        "hotkeys_info": (
            "Hotkeys disabled (F-keys conflict with games)\n"
            "Use the buttons in the interface instead."
        ),
        "scale_group": "Interface settings",
        "lbl_font_size": "Font size:",
        "about_group": "About",
        "about_text": (
            "Screen OCR + TTS v2.0\n"
            "Screen text recognition and speech synthesis.\n"
            "Powered by EasyOCR, Tesseract, Edge-TTS, SAPI."
        ),
        # --- Tray menu ---
        "tray_show": "Show window",
        "tray_scan_all": "Scan all",
        "tray_live": "Live Mode",
        "tray_minimize": "Minimize to tray",
        "tray_quit": "Quit",
        "tray_minimized_title": "Screen OCR + TTS",
        "tray_minimized_body": "Application minimized to tray. Double-click the icon to restore.",
        # --- Context menu ---
        "ctx_edit": "Edit",
        "ctx_delete": "Delete",
        "ctx_scan": "Scan this region",
        "ctx_speak": "Read text",
        "ctx_multi_speak": "Read by roles (multi-voice)",
        "ctx_speech_modes": "Speech mode…",
        "ctx_live": "Scan and speak",
        "ctx_click_through_on": "Click-through: ON",
        "ctx_click_through_off": "Click-through: OFF",
        "ctx_create_new": "Create frame here",
        "ctx_lock": "Lock frame",
        "ctx_unlock": "Unlock frame",
        "ctx_lock_frame": "Lock frame",
        "ctx_unlock_frame": "Unlock frame",
        # --- Dialog titles / messages ---
        "dlg_attention": "Attention",
        "dlg_info": "Info",
        "dlg_confirm": "Confirm",
        "dlg_error": "Error",
        "dlg_save": "Save",
        "dlg_save_audio": "Save audio",
        "dlg_name": "Name",
        "dlg_region_name_prompt": "Region name:",
        "dlg_new_region": "New region",
        "dlg_choose_region": "Choose region",
        "dlg_delete_region": "Delete region",
        "msg_select_region": "Select a region in the list",
        "msg_no_regions": "No saved regions. Create one first.",
        "msg_no_regions_to_scan": "No regions to scan",
        "msg_create_at_least_one": "Create at least one region first",
        "msg_text_empty": "Text is empty.\nFirst recognize text or start Live Mode.",
        "msg_nothing_to_save": "Nothing to save",
        "msg_region_list_prompt": "Region list:\n{names}",
        "msg_delete_confirm": "Delete region '{name}'?",
        "audio_saved_title": "Audio saved",
        "audio_saved_body": "File created:\n{path}\n\nDuration: ~{dur} s",
        "audio_save_failed": "Failed to create audio file:\n{err}",
        "full_screen_name": "Full screen",
        # --- Status messages ---
        "status_recognizing": "Recognizing: {name}...",
        "status_recognized": "OK: {count} chars",
        "status_empty_filtered": "Пусто",
        "status_no_text": "Текст не найден",
        "status_error": "Error: {err}",
        "status_added": "Added: {name}",
        "status_added_size": "Added: {name} ({w}x{h})",
        "status_added_at_cursor": "Added at cursor: {name}",
        "status_selected": "Selected: {name}",
        "status_select_mouse": "Select a region with the mouse... (ESC — cancel)",
        "status_voice_set": "Voice set: {voice}",
        "status_speaking": "Speaking...",
        "status_speaking_text": "Speaking: {text}...",
        "status_test_speaking": "Speaking test phrase...",
        "status_multi_speaking": "Multi-voice speaking...",
        "status_multi_test": "Test multi-voice (SAPI: {count} voices)...",
        "status_generating_audio": "Generating audio...",
        "status_profiles_applied": "Profiles applied: {name}...",
        "status_vlc_started": "VLC streaming started...",
        "status_vlc_stopped": "VLC streaming stopped",
        "status_live_tts_started": "Live TTS started — reading text from the frame",
        "status_live_tts_stopped": "Live TTS stopped",
        "status_live_active": "Live TTS active — speaking text from the frame",
        "status_live_started": "Live OCR + TTS streaming started",
        "status_live_stopped": "Live Mode stopped",
        "status_live_mode_started": "Live Mode started",
        "status_live_for_region": "Live scan: {name}",
        "status_voices_loaded": "Voices loaded: {count}",
        "status_saved_to": "Saved: {path}",
        "status_region_deleted": "Region deleted",
        "status_region_created": "Region created: {name}",
        "status_locked": "Locked",
        "status_unlocked": "Unlocked",
        "status_region_lock_set": "{name}: {status}",
        "status_click_through_set": "'Click-through' for '{name}': {status}",
        "status_edit_on": "Edit mode ON — drag frames to move or resize",
        "status_edit_off": "Edit mode OFF — frames are click-through",
        "status_overlay_hidden": "Frames hidden (Tab to show)",
        "status_overlay_shown": "Frames shown (Tab to hide)",
        "tts_error_prefix": "TTS error: {err}",
        # --- Logs ---
        "log_not_found": "Log file not found. It will appear after the app writes to it.",
        "log_read_error": "Log read error: {err}",
        "log_cleared": "Log cleared.",
        "log_clear_error": "Clear error: {err}",
        "value_on": "ON",
        "value_off": "OFF",
        # --- Test multi-voice sample lines ---
        "sample_narrator_welcome": "Narrator: Welcome to our stream!\n",
        "sample_narrator_welcome_ru": "Narrator: Welcome everyone to the stream!\n",
        "sample_dialogue": (
            "Heroine: Hello everyone! How are you?\n"
            "Hero: Everything is great, thank you!\n"
            "Narrator: And that concludes our program."
        ),
        "test_phrase": "Hello! This is a voice test.",
        "stream_default_text": "Hello! This is a test stream.",
        # --- Voice Profiles tab ---
        "vp_select_voice": "Select voice",
        "vp_voice": "Voice:",
        "vp_params": "Voice parameters",
        "vp_speed": "Speed:",
        "vp_volume": "Volume:",
        "vp_pitch": "Pitch:",
        "vp_apply": "Apply",
        "vp_test": "Test",
        "vp_saved_profiles": "Saved profiles",
        "vp_profile_name_ph": "Profile name...",
        "vp_save": "Save",
        "vp_load": "Load",
        "vp_delete": "Delete",
        "vp_apply_profile": "Apply profile",
        "vp_router": "Routing: language → voice",
        "vp_router_desc": "Select a voice for each language. In multi-voice mode the appropriate voice is chosen automatically.",
        "vp_fallback": "Default voice:",
        "vp_reset_router": "Reset routing",
        "vp_male": "Male",
        "vp_female": "Female",
        "vp_narrator": "Narrator",
        "vp_characters": "Characters (name → voice)",
        "vp_characters_desc": "Set character name and voice. Text 'Name: line' will be read with this voice.",
        "vp_char_name_ph": "Character name...",
        "vp_save_characters": "Save characters",
        "vp_characters_saved": "Characters saved",
        "vp_params_applied": "Parameters applied: {voice}",
        "vp_testing": "Testing: {voice}",
        "vp_enter_name": "Enter a profile name",
        "vp_saved": "Profile '{name}' saved",
        "vp_select_profile": "Select a profile",
        "vp_profile_applied": "Profile '{name}' applied",
        "vp_delete_confirm": "Delete profile '{name}'?",
        "vp_deleted": "Profile '{name}' deleted",
        "vp_router_reset": "Routing reset",
        # --- Translator tab ---
        "tab_translator": "Translator",
        "translator_src_lang": "Source language:",
        "translator_dst_lang": "Target language:",
        "translator_input": "Text to translate:",
        "translator_output": "Translation:",
        "translator_btn_translate": "Translate",
        "translator_btn_speak_src": "Speak source",
        "translator_btn_speak_dst": "Speak translation",
        "translator_auto": "Auto-detect",
        "translator_loading": "Translating...",
        "translator_error": "Translation error: {err}",
        "translator_copy": "Copy translation",
        # --- Translation before TTS ---
        "translation_tts_group": "Translate before TTS",
        "chk_translate_tts": "Translate text before speaking",
        "lbl_translate_dst": "Translate to:",
        "lbl_translate_apikey": "API Key (not needed for Zen):",
        "lbl_translate_model": "Model:",
        "lbl_translate_note": "If API key is empty, Google Translate (free, no key) is used as fallback.",
        "btn_translate_check": "Check connection",
        "translate_check_loading": "Checking...",
        "ctx_translate_speak": "Translate & speak",
        "status_translating": "Translating for TTS...",
        "status_translated_tts": "Translated: {text}...",
    },
    "ru": {
        # --- Window / tabs ---
        "app_title": "Screen OCR + TTS",
        "tab_regions": "Области",
        "tab_scan": "Сканирование",
        "tab_result": "Результат",
        "tab_tts": "TTS",
        "tab_logs": "Логи",
        "tab_settings": "⚙ Настройки",
        "tab_voice_profiles": "Профили голосов",
        "tab_web_live": "Веб-сервер",
        "tab_translator": "Переводчик",
        "offline_tab_info": "Офлайн: EasyOCR + TTS без интернета",
        "online_tab_info": "Онлайн: Edge-TTS + Переводчик + Веб-сервер",
        "combined_tab_info": "Все голоса: Edge (онлайн) + RHVoice/Silero/SAPI5 (офлайн)",
        # --- File manager nav ---
        "cat_main": "Главная",
        "cat_voice": "Голос",
        "cat_translate": "Переводчик",
        "cat_web": "Веб-сервер",
        "cat_settings": "Настройки",
        "cat_logs": "Логи",
        "search_placeholder": "Поиск...",
        "view_grid": "Сетка",
        "view_list": "Список",
        "sort_label": "Сортировка:",
        "sort_importance": "По важности",
        "sort_name": "По имени",
        "sort_recent": "Недавние",
        # --- Status bar ---
        "status_ready": "Готов к работе | Ctrl+перетаскивание — создать рамку",
        "live_off_label": "Live: ВЫКЛ",
        "live_on_label": "Live: ВКЛ",
        "btn_to_tray": "▽ В трей",
        # --- Region dialog ---
        "color_green": "Зелёный",
        "color_blue": "Синий",
        "color_orange": "Оранжевый",
        "color_purple": "Фиолетовый",
        "color_red": "Красный",
        "color_cyan": "Голубой",
        "color_yellow": "Жёлтый",
        "color_white": "Белый",
        "color_black": "Чёрный",
        "color_pink": "Розовый",
        "shape_rect": "Прямоугольник",
        "shape_circle": "Круг",
        "shape_ellipse": "Эллипс",
        "dlg_region_props": "Свойства области",
        "lbl_name": "Название:",
        "lbl_width": "Ш:",
        "lbl_height": "В:",
        "lbl_frame_color": "Цвет рамки:",
        "lbl_frame_shape": "Форма рамки:",
        "chk_click_through": "Сквозной клик (без перехвата мыши/клавиатуры)",
        "tip_click_through": "Когда включено, рамка не перехватывает клики и ввод с клавиатуры",
        "lbl_tts_voice": "Голос TTS:",
        "region_default_name": "R{x}",
        # --- Regions tab ---
        "regions_hint": "Ctrl+перетаскивание для создания рамки",
        "regions_list_group": "Список областей",
        "btn_edit_mode_on": "Режим редактирования: ВКЛ",
        "btn_edit_mode_off": "Режим редактирования: ВЫКЛ",
        "btn_add": "Добавить",
        "btn_edit": "Изменить",
        "btn_delete": "Удалить",
        # --- Scan tab ---
        "ocr_settings_group": "Настройки OCR",
        "lbl_language": "Язык:",
        "lbl_engine": "Движок:",
        "lbl_content_preset": "Пресет контента:",
        "live_mode_group": "Live Mode",
        "chk_enable_live": "Включить Live Mode",
        "lbl_interval": "Интервал:",
        "suffix_ms": " мс",
        "chk_detect_changes": "Отслеживать изменения",
        "scan_mode_group": "Режим сканирования",
        "lbl_scan_mode": "Режим:",
        "scan_mode_normal": "Обычный (по запросу)",
        "scan_mode_realtime_clear": "Реальное время (очищать предыдущее)",
        "scan_mode_realtime_keep": "Реальное время (накапливать)",
        "chk_separate_regions": "Отдельный результат по регионам",
        "status_speech_started": "Режим озвучки {mode} включён",
        "status_speech_stopped": "Режим озвучки {mode} остановлен",
        "speech_modes_group": "Режимы озвучки (горячие клавиши 1-4)",
        "speech_mode_1": "1: Один голос",
        "speech_mode_2": "2: Мультиголос",
        "speech_mode_3": "3: Реальное время, один голос",
        "speech_mode_4": "4: Реальное время, по ролям",
        "speech_mode_none": "Озвучка: ВЫКЛ",
        "speech_mode_active": "Озвучка: режим {mode} АКТИВЕН",
        "chk_web_tts": "Веб-сервер TTS (SAPI)",
        "status_web_tts_on": "Веб-сервер TTS запущен на порту {port}",
        "status_web_tts_off": "Веб-сервер TTS остановлен",
        "tab_web_live": "Live TTS (Веб)",
        "web_live_hint": "Озвучка голосом браузера (Алиса в Яндекс.Браузере)",
        "scan_group": "Сканирование",
        "btn_scan_selected": "Сканировать выбранную",
        "btn_scan_all": "Сканировать все",
        "live_tts_group": "Live TTS (непрерывное чтение)",
        "btn_start_live_tts": "▶ Запустить Live TTS",
        "btn_stop_live_tts": "■ Остановить (1)",
        "live_tts_idle": "Ожидание",
        "live_tts_active": "Активно",
        "line_by_line_group": "Построчный режим",
        "chk_line_by_line": "Озвучивать построчно (мгновенно)",
        "tip_line_by_line": "Каждая новая строка текста озвучивается сразу, не дожидаясь следующего сканирования",
        "line_by_line_active": "Активен",
        "sync_group": "Синхронизация голоса",
        "chk_sync_mode": "Голос = приоритет (скан ждёт озвучки)",
        "sentence_group": "Пофразовое чтение",
        "chk_sentence_mode": "Читать по предложениям (текст стирается)",
        # --- Result tab ---
        "result_group": "Распознанный текст (редактируемый)",
        "btn_speak": "Озвучить",
        "btn_save_audio": "Сохранить аудио",
        "btn_save_txt": "Сохранить .txt",
        "btn_copy": "Копировать",
        "btn_clear": "Очистить",
        "btn_stop_speaking": "Стоп",
        "btn_instant_speak": "Мгновенно",
        "btn_test_dialogue": "Тест диалога",
        "status_instant_speaking": "Мгновенное чтение...",
        "status_multi_test": "Диалог...",
        # --- TTS tab ---
        "voice_default_group": "Голос по умолчанию",
        "lbl_voice": "Голос:",
        "speed_group": "Скорость",
        "volume_group": "Громкость",
        "playback_engine_group": "Движок воспроизведения",
        "engine_edge_playback": "edge-playback (быстрый, простой)",
        "engine_edge_vlc": "Edge-TTS → MP3 → VLC (потоковое радио)",
        "engine_sapi": "Windows Speech API (офлайн)",
        "btn_save_mp3": "Сохранить в MP3",
        "vlc_stream_group": "VLC стриминг (радио)",
        "btn_start_stream": "▶ Запустить стрим",
        "btn_stop_stream": "■ Остановить стрим",
        "btn_test_voice": "Тест голоса",
        "multi_voice_group": "Многоголосый режим",
        "chk_enable_multi_voice": "Включить многоголосый режим",
        "profiles_group": "Профили голосов",
        "voice_roles_group": "Голоса для ролей",
        "lbl_male_voice": "Мужской:",
        "lbl_female_voice": "Женский:",
        "lbl_narrator": "Рассказчик:",
        "voice_settings": "Настройки",
        "lbl_speed": "Скорость:",
        "lbl_pitch": "Питч:",
        "btn_test_this_voice": "Тест этого голоса",
        "profile_name_ph": "Имя профиля...",
        "btn_save_profile": "Сохранить",
        "btn_load_profile": "Загрузить",
        "btn_del_profile": "Удалить",
        "lbl_heroine": "Героиня:",
        "lbl_hero": "Герой:",
        "btn_apply_profiles": "Применить профили",
        "btn_test_multi": "Тест многоголосого",
        "multi_voice_hint": "Формат: Имя: текст (например, Привет!)",
        # --- Logs tab ---
        "btn_refresh": "Обновить",
        "chk_auto_refresh": "Автообновление (5 с)",
        "btn_clear_logs": "Очистить лог",
        # --- Settings tab ---
        "settings_ocr_group": "Настройки OCR",
        "chk_use_gpu": "Использовать GPU (CUDA)",
        "lbl_confidence": "Порог уверенности:",
        "lbl_scan_interval": "Интервал сканирования:",
        "chk_detect_changes_detect": "Отслеживать изменения кадра",
        "lbl_change_threshold": "Чувствительность изменений:",
        "chk_auto_detect_region": "Автоопределение области текста",
        "settings_tts_group": "Настройки TTS",
        "lbl_voice_type": "Тип голоса:",
        "chk_cache_audio": "Кэшировать аудио",
        "lbl_rate": "Скорость речи:",
        "lbl_volume": "Громкость:",
        "chk_multi_voice_mode": "Многоголосый режим (автоопределение языка)",
        "sapi_voices_loading": "SAPI голоса: загрузка...",
        "sapi_voices_none": "SAPI голоса не найдены",
        "sapi_voices_prefix": "SAPI: ",
        "settings_overlay_group": "Оверлей / Отображение на экране",
        "chk_overlay_enabled": "Показывать оверлей",
        "chk_overlay_text": "Показывать распознанный текст",
        "lbl_opacity": "Прозрачность рамок:",
        "lbl_panel_opacity": "Прозрачность панелей:",
        "lbl_overlay_font_size": "Размер шрифта:",
        "lbl_font_color": "Цвет текста:",
        "lbl_bg_color": "Цвет фона:",
        "lbl_position": "Позиция:",
        "settings_general_group": "Общие",
        "chk_start_minimized": "Запускать свёрнутым в трей",
        "chk_log_enabled": "Включить логирование в файл",
        "lbl_log_level": "Уровень лога:",
        "settings_web_tts_group": "Веб-сервер TTS",
        "lbl_web_tts_port": "Порт:",
        "hotkeys_group": "Горячие клавиши",
        "hotkeys_info": (
            "Горячие клавиши отключены (F-клавиши конфликтуют с играми)\n"
            "Используйте кнопки в интерфейсе."
        ),
        "scale_group": "Настройки интерфейса",
        "lbl_font_size": "Размер шрифта:",
        "about_group": "О программе",
        "about_text": (
            "Screen OCR + TTS v2.0\n"
            "Распознавание текста с экрана и синтез речи.\n"
            "Используются EasyOCR, Tesseract, Edge-TTS, SAPI."
        ),
        # --- Tray menu ---
        "tray_show": "Показать окно",
        "tray_scan_all": "Сканировать все",
        "tray_live": "Live Mode",
        "tray_minimize": "Свернуть в трей",
        "tray_quit": "Выход",
        "tray_minimized_title": "Screen OCR + TTS",
        "tray_minimized_body": "Приложение свёрнуто в трей. Дважды кликните по значку для восстановления.",
        # --- Context menu ---
        "ctx_edit": "Редактировать",
        "ctx_delete": "Удалить",
        "ctx_scan": "Сканировать эту область",
        "ctx_speak": "Озвучить текст",
        "ctx_multi_speak": "Читать по ролям (многоголосый)",
        "ctx_speech_modes": "Режим озвучки…",
            "ctx_live": "Сканировать и озвучить",
        "ctx_click_through_on": "Сквозной клик: ВКЛ",
        "ctx_click_through_off": "Сквозной клик: ВЫКЛ",
        "ctx_create_new": "Создать рамку здесь",
        "ctx_lock": "Зафиксировать рамку",
        "ctx_unlock": "Разблокировать рамку",
        "ctx_lock_frame": "Зафиксировать рамку",
        "ctx_unlock_frame": "Разблокировать рамку",
        # --- Dialog titles / messages ---
        "dlg_attention": "Внимание",
        "dlg_info": "Информация",
        "dlg_confirm": "Подтверждение",
        "dlg_error": "Ошибка",
        "dlg_save": "Сохранить",
        "dlg_save_audio": "Сохранить аудио",
        "dlg_name": "Название",
        "dlg_region_name_prompt": "Название области:",
        "dlg_new_region": "Новая область",
        "dlg_choose_region": "Выбор области",
        "dlg_delete_region": "Удалить область",
        "msg_select_region": "Выберите область в списке",
        "msg_no_regions": "Нет сохранённых областей. Сначала создайте область.",
        "msg_no_regions_to_scan": "Нет областей для сканирования",
        "msg_create_at_least_one": "Сначала создайте хотя бы одну область",
        "msg_text_empty": "Текст пуст.\nСначала распознайте текст или запустите Live Mode.",
        "msg_nothing_to_save": "Нечего сохранять",
        "msg_region_list_prompt": "Список областей:\n{names}",
        "msg_delete_confirm": "Удалить область '{name}'?",
        "audio_saved_title": "Аудио сохранено",
        "audio_saved_body": "Файл создан:\n{path}\n\nДлительность: ~{dur} с",
        "audio_save_failed": "Не удалось создать аудиофайл:\n{err}",
        "full_screen_name": "Весь экран",
        # --- Status messages ---
        "status_recognizing": "Распознавание: {name}...",
        "status_recognized": "OK: {count}",
        "status_empty_filtered": "Пусто",
        "status_no_text": "Текст не найден",
        "status_error": "Ошибка: {err}",
        "status_added": "Добавлено: {name}",
        "status_added_size": "Добавлено: {name} ({w}x{h})",
        "status_added_at_cursor": "Добавлено по курсору: {name}",
        "status_selected": "Выбрано: {name}",
        "status_select_mouse": "Выберите область мышью... (ESC — отмена)",
        "status_voice_set": "Голос выбран: {voice}",
        "status_speaking": "Озвучивание...",
        "status_speaking_text": "Озвучивание: {text}...",
        "status_test_speaking": "Озвучивание тестовой фразы...",
        "status_multi_speaking": "Многоголосое озвучивание...",
        "status_multi_test": "Тест многоголосого (SAPI: {count} голосов)...",
        "status_generating_audio": "Генерация аудио...",
        "status_profiles_applied": "Профили применены: {name}...",
        "status_vlc_started": "VLC стриминг запущен...",
        "status_vlc_stopped": "VLC стриминг остановлен",
        "status_live_tts_started": "Live TTS запущен — чтение текста из рамки",
        "status_live_tts_stopped": "Live TTS остановлен",
        "status_live_active": "Live TTS активен — озвучивание текста из рамки",
        "status_live_started": "Live OCR + TTS стриминг запущен",
        "status_live_stopped": "Live Mode остановлен",
        "status_live_mode_started": "Live Mode запущен",
        "status_live_for_region": "Live-сканирование: {name}",
        "status_voices_loaded": "Голосов загружено: {count}",
        "status_saved_to": "Сохранено: {path}",
        "status_region_deleted": "Область удалена",
        "status_region_created": "Область создана: {name}",
        "status_locked": "Зафиксирована",
        "status_unlocked": "Разблокирована",
        "status_region_lock_set": "{name}: {status}",
        "status_click_through_set": "'Сквозной клик' для '{name}': {status}",
        "status_edit_on": "Режим редактирования ВКЛ — перетаскивайте рамки для перемещения и изменения размера",
        "status_edit_off": "Режим редактирования ВЫКЛ — рамки сквозные для кликов",
        "status_overlay_hidden": "Рамки скрыты (Tab для показа)",
        "status_overlay_shown": "Рамки показаны (Tab для скрытия)",
        "tts_error_prefix": "Ошибка TTS: {err}",
        # --- Logs ---
        "log_not_found": "Файл лога не найден. Он появится после первой записи приложения.",
        "log_read_error": "Ошибка чтения лога: {err}",
        "log_cleared": "Лог очищен.",
        "log_clear_error": "Ошибка очистки: {err}",
        "value_on": "ВКЛ",
        "value_off": "ВЫКЛ",
        # --- Test multi-voice sample lines ---
        "sample_narrator_welcome": "Рассказчик: Добро пожаловать на наш стрим!\n",
        "sample_narrator_welcome_ru": "Рассказчик: Добро пожаловать всем на стрим!\n",
        "sample_dialogue": (
            "Героиня: Всем привет! Как дела?\n"
            "Герой: Всё отлично, спасибо!\n"
            "Рассказчик: На этом наша программа завершается."
        ),
        "test_phrase": "Привет! Это тест голоса.",
        "stream_default_text": "Привет! Это тестовый стрим.",
        # --- Voice Profiles tab ---
        "vp_select_voice": "Выбор голоса",
        "vp_voice": "Голос:",
        "vp_params": "Параметры голоса",
        "vp_speed": "Скорость:",
        "vp_volume": "Громкость:",
        "vp_pitch": "Питч:",
        "vp_apply": "Применить",
        "vp_test": "Тест",
        "vp_saved_profiles": "Сохранённые профили",
        "vp_profile_name_ph": "Имя профиля...",
        "vp_save": "Сохранить",
        "vp_load": "Загрузить",
        "vp_delete": "Удалить",
        "vp_apply_profile": "Применить профиль",
        "vp_router": "Маршрутизация: язык → голос",
        "vp_router_desc": "Выберите голос для каждого языка. При мультиголосовом режиме автоматически подбирается нужный голос.",
        "vp_fallback": "Голос по умолчанию:",
        "vp_reset_router": "Сбросить маршрутизацию",
        "vp_male": "Мужчина",
        "vp_female": "Девушка",
        "vp_narrator": "Рассказчик",
        "vp_characters": "Персонажи (имя → голос)",
        "vp_characters_desc": "Задайте имя персонажа и голос. Текст «Имя: реплика» будет озвучен этим голосом.",
        "vp_char_name_ph": "Имя персонажа...",
        "vp_save_characters": "Сохранить персонажей",
        "vp_characters_saved": "Персонажи сохранены",
        "vp_params_applied": "Параметры применены: {voice}",
        "vp_testing": "Тест: {voice}",
        "vp_enter_name": "Введите имя профиля",
        "vp_saved": "Профиль «{name}» сохранён",
        "vp_select_profile": "Выберите профиль",
        "vp_profile_applied": "Профиль «{name}» применён",
        "vp_delete_confirm": "Удалить профиль «{name}»?",
        "vp_deleted": "Профиль «{name}» удалён",
        "vp_router_reset": "Маршрутизация сброшена",
        # --- Translator tab ---
        "tab_translator": "Переводчик",
        "translator_src_lang": "Язык источника:",
        "translator_dst_lang": "Язык перевода:",
        "translator_input": "Текст для перевода:",
        "translator_output": "Перевод:",
        "translator_btn_translate": "Перевести",
        "translator_btn_speak_src": "Озвучить исходный",
        "translator_btn_speak_dst": "Озвучить перевод",
        "translator_auto": "Автоопределение",
        "translator_loading": "Перевод...",
        "translator_error": "Ошибка перевода: {err}",
        "translator_copy": "Копировать перевод",
        # --- Translation before TTS ---
        "translation_tts_group": "Перевод перед озвучкой",
        "chk_translate_tts": "Переводить текст перед озвучкой",
        "lbl_translate_dst": "Переводить на:",
        "lbl_translate_apikey": "API-ключ (для Zen не нужен):",
        "lbl_translate_model": "Модель:",
        "lbl_translate_note": "Если ключ пуст, используется Google Translate (бесплатно, без ключа).",
        "btn_translate_check": "Проверить соединение",
        "translate_check_loading": "Проверка...",
        "ctx_translate_speak": "Перевести и озвучить",
        "status_translating": "Перевод для TTS...",
        "status_translated_tts": "Переведено: {text}...",
    },
}
