# -*- coding: utf-8 -*-
PHRASES = {
    "hello":"привет","goodbye":"до свидания",
    "bye":"пока","see you":"увидимся","see you later":"увидимся позже",
    "good morning":"доброе утро","good afternoon":"добрый день",
    "good evening":"добрый вечер","good night":"спокойной ночи",
    "how are you":"как дела","how are you doing":"как дела",
    "i'm fine":"я в порядке","thank you":"спасибо","thanks":"спасибо",
    "please":"пожалуйста","excuse me":"извините",
    "i'm sorry":"прости меня","sorry":"прости",
    "yes":"да","no":"нет","maybe":"может быть",
    "i don't understand":"я не понимаю","i understand":"я понимаю",
    "help me":"помоги мне","help me please":"пожалуйста помоги мне",
    "follow me":"следуй за мной","follow me right now":"следуй за мной прямо сейчас",
    "wait":"подожди","wait here":"подожди здесь","come here":"иди сюда",
    "go away":"уходи","get out":"выходи","come back":"вернись",
    "come back quickly":"вернись быстро","hurry":"поспешить",
    "danger":"опасность","be careful":"будь осторожен",
    "watch out":"осторожно","look out":"осторожно",
    "i need help":"мне нужна помощь","i need you":"ты мне нужен",
    "we need to go":"нам нужно идти","we must go":"мы должны уйти",
    "we should go":"нам стоит уйти","let's go":"пойдём",
    "let's go now":"пойдём сейчас","we have to leave":"нам нужно уйти",
    "where is":"где находится","where are you":"где ты",
    "what is":"что это","what happened":"что произошло",
    "who are you":"кто ты","who is that":"кто это",
    "why":"почему","when":"когда","how":"как",
    "give me":"дай мне","give me the key":"дай мне ключ",
    "i want":"я хочу","i need":"мне нужно",
    "i have":"у меня есть","i don't have":"у меня нет",
    "i am":"я есть","you are":"ты есть","he is":"он есть",
    "she is":"она есть","it is":"это есть","we are":"мы есть",
    "they are":"они есть","i was":"я был","you were":"ты был",
    "he was":"он был","she was":"она былa",
    "we were":"мы были","they were":"они были",
    "attack":"атаковать","attack the enemy":"атакуй врага",
    "defend":"защищать","defend yourself":"защищайся",
    "fight":"сражаться","run":"беги","hide":"спрячься",
    "stay here":"останься здесь","don't move":"не двигайся",
    "come with me":"иди со мной","go with him":"иди с ним",
    "once upon a time":"давным-давно","long long ago":"очень давно",
    "the end":"конец","the beginning":"начало",
    "good":"хорошо","bad":"плохо","great":"отлично","fantastic":"фантастика",
    "wonderful":"замечательно","terrible":"ужасно","awful":"кошмар",
    "beautiful":"красивый","ugly":"уродливый","strong":"сильный",
    "weak":"слабый","fast":"быстрый","slow":"медленный",
    "big":"большой","small":"маленький","old":"старый","new":"новый",
    "young":"молодой","tall":"высокий","short":"низкий",
    "friend":"друг","enemy":"враг","hero":"герой","monster":"монстр",
    "king":"король","queen":"королева","prince":"принц","princess":"принцесса",
    "knight":"рыцарь","wizard":"волшебник","mage":"маг","warrior":"воин",
    "thief":"вор","assassin":"убийца","archer":"стрелок","healer":"целитель",
    "sword":"меч","shield":"щит","armor":"броня","weapon":"оружие",
    "magic":"магия","spell":"заклинание","potion":"зелье",
    "health":"здоровье","mana":"мана","power":"сила","level":"уровень",
    "quest":"квест","mission":"миссия","battle":"битва","war":"война",
    "peace":"мир","death":"смерть","life":"жизнь","soul":"душа",
    "light":"свет","dark":"тьма","fire":"огонь","water":"вода",
    "earth":"земля","wind":"ветер","sky":"небо","star":"звезда",
    "moon":"луна","sun":"солнце","night":"ночь","day":"день",
    "morning":"утро","evening":"вечер","world":"мир","land":"земля",
    "forest":"лес","mountain":"гора","river":"река","sea":"море",
    "ocean":"океан","island":"остров","city":"город","town":"деревня",
    "castle":"замок","tower":"башня","dungeon":"подземелье",
    "village":"деревня","temple":"храм","palace":"дворец",
    "blood":"кровь","wound":"рана","pain":"боль","fear":"страх",
    "courage":"мужество","hope":"надежда","faith":"вера","love":"любовь",
    "hatred":"ненависть","anger":"гнев","joy":"радость","sadness":"грусть",
    "truth":"правда","lie":"ложь","secret":"секрет","promise":"обещание",
    "oath":"клятва","destiny":"судьба","fate":"судьба","doom":"гибель",
    "power":"власть","throne":"трон","crown":"корона","kingdom":"королевство",
    "empire":"империя","republic":"республика","army":"армия","soldier":"солдат",
    "commander":"командир","captain":"капитан","general":"генерал",
    "prison":"тюрьма","escape":"побег","capture":"поимка",
    "treasure":"сокровище","gold":"золото","silver":"серебро","diamond":"алмаз",
    "ancient":"древний","powerful":"могущественный","dangerous":"опасный",
    "brave":"храбрый","loyal":"верный","evil":"злой","dark":"тёмный",
    "light":"светлый","shadow":"тень","ghost":"призрак","dragon":"дракон",
    "demon":"демон","angel":"ангел","god":"бог","devil":"дьявол",
    "fate":"судьба","war":"война","peace":"мир","king":"король",
    "queen":"королева","throne":"трон","sword":"меч","shield":"щит",
    "quest":"квест","dungeon":"подземелье","treasure":"сокровище",
    "they are enemies":"они враги","we are friends":"мы друзья",
    "he is strong":"он силен","she is beautiful":"она красива",
    "i am scared":"я напуган","it is dangerous":"это опасно",
    "come back quickly":"вернись быстро",
    "once upon a time":"давным-давно",
    "the hero found a magic sword":"герой нашёл волшебный меч",
    "attack the enemy":"атакуй врага",
    "follow me right now":"следуй за мной прямо сейчас",
    "good morning":"доброе утро","i love you":"я люблю тебя",
    "where is the sword":"где меч","i need a potion":"мне нужно зелье",
    "that is great":"это отлично","i am lost":"я заблудился",
    "give me the key":"дай мне ключ",
    "the detective found a clue":"детектив нашёл улику",
    "who is the suspect":"кто подозреваемый",
    "she was found dead":"её нашли мёртвой",
    "search the crime scene":"обыщи место преступления",
    "we need evidence":"нам нужны доказательства",
    "he was murdered":"его убили",
    "find the murder weapon":"найди оружие убийства",
    "what is the motive":"какой мотив",
    "i need a warrant":"мне нужен ордер",
    "call the police":"вызови полицию",
    "check the alibi":"проверь алиби",
    "the suspect fled":"подозреваемый сбежал",
    "he was arrested":"его арестовали",
    "the jury found him guilty":"жюри признало его виновным",
    "the judge sentenced him":"судья приговорил его",
    "he was acquitted":"его оправдали",
    "the appeal was denied":"апелляция отклонена",
    "the killer escaped":"убийца сбежал",
    "he confessed to the murder":"он признался в убийстве",
    "the police arrested him":"полиция арестовала его",
    "the case was closed":"дело закрыто",
}
