package com.screenocr.client.dict

// СГЕНЕРИРОВАНО: python3 gen_android_dicts.py
// Источники: phrases_dict.py, words_extra.py, contractions.py
// Правь источники и перегенерируй — руками этот файл не меняем.

object DictData {

    // Порядок важен: замены идут подряд, как str.replace в Python.
    val CONTRACTIONS: List<Pair<String, String>> = listOf(
        "let's" to "let us",
        "don't" to "do not",
        "doesn't" to "does not",
        "didn't" to "did not",
        "won't" to "will not",
        "can't" to "cannot",
        "couldn't" to "could not",
        "wouldn't" to "would not",
        "shouldn't" to "should not",
        "isn't" to "is not",
        "aren't" to "are not",
        "wasn't" to "was not",
        "weren't" to "were not",
        "haven't" to "have not",
        "hasn't" to "has not",
        "hadn't" to "had not",
        "i'm" to "i am",
        "you're" to "you are",
        "he's" to "he is",
        "she's" to "she is",
        "it's" to "it is",
        "we're" to "we are",
        "they're" to "they are",
        "i've" to "i have",
        "you've" to "you have",
        "we've" to "we have",
        "they've" to "they have",
        "i'll" to "i will",
        "you'll" to "you will",
        "he'll" to "he will",
        "she'll" to "she will",
        "we'll" to "we will",
        "they'll" to "they will",
        "i'd" to "i would",
        "you'd" to "you would",
        "he'd" to "he would",
        "she'd" to "she would",
        "we'd" to "we would",
        "they'd" to "they would",
        "that's" to "that is",
        "what's" to "what is",
        "who's" to "who is",
        "where's" to "where is",
        "when's" to "when is",
        "how's" to "how is",
        "there's" to "there is",
        "here's" to "here is",
    )

    val PHRASES: Map<String, String> = mapOf(
        "hello" to "привет",
        "goodbye" to "до свидания",
        "bye" to "пока",
        "see you" to "увидимся",
        "see you later" to "увидимся позже",
        "good morning" to "доброе утро",
        "good afternoon" to "добрый день",
        "good evening" to "добрый вечер",
        "good night" to "спокойной ночи",
        "how are you" to "как дела",
        "how are you doing" to "как дела",
        "i'm fine" to "я в порядке",
        "thank you" to "спасибо",
        "thanks" to "спасибо",
        "please" to "пожалуйста",
        "excuse me" to "извините",
        "i'm sorry" to "прости меня",
        "sorry" to "прости",
        "yes" to "да",
        "no" to "нет",
        "maybe" to "может быть",
        "i don't understand" to "я не понимаю",
        "i understand" to "я понимаю",
        "help me" to "помоги мне",
        "help me please" to "пожалуйста помоги мне",
        "follow me" to "следуй за мной",
        "follow me right now" to "следуй за мной прямо сейчас",
        "wait" to "подожди",
        "wait here" to "подожди здесь",
        "come here" to "иди сюда",
        "go away" to "уходи",
        "get out" to "выходи",
        "come back" to "вернись",
        "come back quickly" to "вернись быстро",
        "hurry" to "поспешить",
        "danger" to "опасность",
        "be careful" to "будь осторожен",
        "watch out" to "осторожно",
        "look out" to "осторожно",
        "i need help" to "мне нужна помощь",
        "i need you" to "ты мне нужен",
        "we need to go" to "нам нужно идти",
        "we must go" to "мы должны уйти",
        "we should go" to "нам стоит уйти",
        "let's go" to "пойдём",
        "let's go now" to "пойдём сейчас",
        "we have to leave" to "нам нужно уйти",
        "where is" to "где находится",
        "where are you" to "где ты",
        "what is" to "что это",
        "what happened" to "что произошло",
        "who are you" to "кто ты",
        "who is that" to "кто это",
        "why" to "почему",
        "when" to "когда",
        "how" to "как",
        "give me" to "дай мне",
        "give me the key" to "дай мне ключ",
        "i want" to "я хочу",
        "i need" to "мне нужно",
        "i have" to "у меня есть",
        "i don't have" to "у меня нет",
        "i am" to "я есть",
        "you are" to "ты есть",
        "he is" to "он есть",
        "she is" to "она есть",
        "it is" to "это есть",
        "we are" to "мы есть",
        "they are" to "они есть",
        "i was" to "я был",
        "you were" to "ты был",
        "he was" to "он был",
        "she was" to "она былa",
        "we were" to "мы были",
        "they were" to "они были",
        "attack" to "атаковать",
        "attack the enemy" to "атакуй врага",
        "defend" to "защищать",
        "defend yourself" to "защищайся",
        "fight" to "сражаться",
        "run" to "беги",
        "hide" to "спрячься",
        "stay here" to "останься здесь",
        "don't move" to "не двигайся",
        "come with me" to "иди со мной",
        "go with him" to "иди с ним",
        "once upon a time" to "давным-давно",
        "long long ago" to "очень давно",
        "the end" to "конец",
        "the beginning" to "начало",
        "good" to "хорошо",
        "bad" to "плохо",
        "great" to "отлично",
        "fantastic" to "фантастика",
        "wonderful" to "замечательно",
        "terrible" to "ужасно",
        "awful" to "кошмар",
        "beautiful" to "красивый",
        "ugly" to "уродливый",
        "strong" to "сильный",
        "weak" to "слабый",
        "fast" to "быстрый",
        "slow" to "медленный",
        "big" to "большой",
        "small" to "маленький",
        "old" to "старый",
        "new" to "новый",
        "young" to "молодой",
        "tall" to "высокий",
        "short" to "низкий",
        "friend" to "друг",
        "enemy" to "враг",
        "hero" to "герой",
        "monster" to "монстр",
        "king" to "король",
        "queen" to "королева",
        "prince" to "принц",
        "princess" to "принцесса",
        "knight" to "рыцарь",
        "wizard" to "волшебник",
        "mage" to "маг",
        "warrior" to "воин",
        "thief" to "вор",
        "assassin" to "убийца",
        "archer" to "стрелок",
        "healer" to "целитель",
        "sword" to "меч",
        "shield" to "щит",
        "armor" to "броня",
        "weapon" to "оружие",
        "magic" to "магия",
        "spell" to "заклинание",
        "potion" to "зелье",
        "health" to "здоровье",
        "mana" to "мана",
        "power" to "власть",
        "level" to "уровень",
        "quest" to "квест",
        "mission" to "миссия",
        "battle" to "битва",
        "war" to "война",
        "peace" to "мир",
        "death" to "смерть",
        "life" to "жизнь",
        "soul" to "душа",
        "light" to "светлый",
        "dark" to "тёмный",
        "fire" to "огонь",
        "water" to "вода",
        "earth" to "земля",
        "wind" to "ветер",
        "sky" to "небо",
        "star" to "звезда",
        "moon" to "луна",
        "sun" to "солнце",
        "night" to "ночь",
        "day" to "день",
        "morning" to "утро",
        "evening" to "вечер",
        "world" to "мир",
        "land" to "земля",
        "forest" to "лес",
        "mountain" to "гора",
        "river" to "река",
        "sea" to "море",
        "ocean" to "океан",
        "island" to "остров",
        "city" to "город",
        "town" to "деревня",
        "castle" to "замок",
        "tower" to "башня",
        "dungeon" to "подземелье",
        "village" to "деревня",
        "temple" to "храм",
        "palace" to "дворец",
        "blood" to "кровь",
        "wound" to "рана",
        "pain" to "боль",
        "fear" to "страх",
        "courage" to "мужество",
        "hope" to "надежда",
        "faith" to "вера",
        "love" to "любовь",
        "hatred" to "ненависть",
        "anger" to "гнев",
        "joy" to "радость",
        "sadness" to "грусть",
        "truth" to "правда",
        "lie" to "ложь",
        "secret" to "секрет",
        "promise" to "обещание",
        "oath" to "клятва",
        "destiny" to "судьба",
        "fate" to "судьба",
        "doom" to "гибель",
        "throne" to "трон",
        "crown" to "корона",
        "kingdom" to "королевство",
        "empire" to "империя",
        "republic" to "республика",
        "army" to "армия",
        "soldier" to "солдат",
        "commander" to "командир",
        "captain" to "капитан",
        "general" to "генерал",
        "prison" to "тюрьма",
        "escape" to "побег",
        "capture" to "поимка",
        "treasure" to "сокровище",
        "gold" to "золото",
        "silver" to "серебро",
        "diamond" to "алмаз",
        "ancient" to "древний",
        "powerful" to "могущественный",
        "dangerous" to "опасный",
        "brave" to "храбрый",
        "loyal" to "верный",
        "evil" to "злой",
        "shadow" to "тень",
        "ghost" to "призрак",
        "dragon" to "дракон",
        "demon" to "демон",
        "angel" to "ангел",
        "god" to "бог",
        "devil" to "дьявол",
        "they are enemies" to "они враги",
        "we are friends" to "мы друзья",
        "he is strong" to "он силен",
        "she is beautiful" to "она красива",
        "i am scared" to "я напуган",
        "it is dangerous" to "это опасно",
        "the hero found a magic sword" to "герой нашёл волшебный меч",
        "i love you" to "я люблю тебя",
        "where is the sword" to "где меч",
        "i need a potion" to "мне нужно зелье",
        "that is great" to "это отлично",
        "i am lost" to "я заблудился",
        "the detective found a clue" to "детектив нашёл улику",
        "who is the suspect" to "кто подозреваемый",
        "she was found dead" to "её нашли мёртвой",
        "search the crime scene" to "обыщи место преступления",
        "we need evidence" to "нам нужны доказательства",
        "he was murdered" to "его убили",
        "find the murder weapon" to "найди оружие убийства",
        "what is the motive" to "какой мотив",
        "i need a warrant" to "мне нужен ордер",
        "call the police" to "вызови полицию",
        "check the alibi" to "проверь алиби",
        "the suspect fled" to "подозреваемый сбежал",
        "he was arrested" to "его арестовали",
        "the jury found him guilty" to "жюри признало его виновным",
        "the judge sentenced him" to "судья приговорил его",
        "he was acquitted" to "его оправдали",
        "the appeal was denied" to "апелляция отклонена",
        "the killer escaped" to "убийца сбежал",
        "he confessed to the murder" to "он признался в убийстве",
        "the police arrested him" to "полиция арестовала его",
        "the case was closed" to "дело закрыто",
    )

    val EXTRA_WORDS: Map<String, String> = mapOf(
        "fingerprints" to "отпечатки пальцев",
        "fingerprint" to "отпечаток пальца",
        "oclock" to "часов",
        "o'clock" to "часов",
        "claimed" to "утверждала",
        "claim" to "утверждать",
        "reexamined" to "пересмотрел",
        "reexamine" to "пересмотреть",
        "confronted" to "столкнулась",
        "confront" to "столкнуться",
        "recovered" to "извлекли",
        "recover" to "извлечь",
        "relieved" to "облегчена",
        "relieve" to "облегчить",
        "hardest" to "самый трудный",
        "hard" to "трудный",
        "reporters" to "репортёры",
        "reporter" to "репортёр",
        "thanked" to "поблагодарил",
        "thank" to "поблагодарить",
        "dedication" to "преданность",
        "dedicate" to "посвятить",
        "praised" to "хвалил",
        "praise" to "хвалить",
        "bestseller" to "бестселлер",
        "accuracy" to "точность",
        "accurate" to "точный",
        "attention" to "внимание",
        "detail" to "деталь",
        "mostly" to "в основном",
        "served" to "прослужила",
        "serve" to "служить",
        "released" to "освобождена",
        "release" to "освободить",
        "louder" to "громче",
        "loud" to "громкий",
        "smallest" to "самый маленький",
        "small" to "маленький",
        "crack" to "взломать",
        "figure" to "фигура",
        "exactly" to "точно",
        "twelve" to "двенадцать",
        "ten" to "десять",
        "building" to "здание",
        "scream" to "крик",
        "diary" to "дневник",
        "entries" to "записи",
        "secret" to "секрет",
        "meeting" to "встреча",
        "shadows" to "тени",
        "shadow" to "тень",
        "jealous" to "ревнивый",
        "jealousy" to "ревность",
        "lover" to "любовник",
        "mistress" to "хозяйка",
        "jail" to "тюрьма",
        "justice" to "справедливость",
        "filed" to "подала",
        "textbook" to "учебник",
        "academy" to "академия",
        "press" to "пресса",
        "conference" to "конференция",
        "calm" to "спокойно",
        "persistence" to "настойчивость",
        "crucial" to "решающий",
        "conviction" to "осуждение",
        "commendation" to "похвала",
        "promoted" to "повышен",
        "divers" to "водолазы",
        "matched" to "совпадали",
        "arrived" to "прибыл",
        "arrive" to "прибыть",
        "suspect" to "подозреваемый",
        "suspects" to "подозреваемые",
        "sherman" to "Шерман",
        "holmes" to "Холмс",
        "lestrade" to "Лестрейд",
        "grayson" to "Грейсон",
        "catherine" to "Кэтрин",
        "morland" to "Морленд",
        "sherlock" to "Шерлок",
        "watson" to "Ватсон",
        "parker" to "Паркер",
        "should" to "должен",
        "could" to "мог бы",
        "would" to "бы",
        "might" to "бы может",
        "may" to "может",
        "can" to "может",
        "will" to "будет",
        "shall" to "будет",
        "must" to "должен",
        "away" to "прочь",
        "far" to "далеко",
        "near" to "близко",
        "here" to "здесь",
        "there" to "там",
        "home" to "дома",
        "inside" to "внутри",
        "outside" to "снаружи",
        "between" to "между",
        "during" to "во время",
        "until" to "до",
        "since" to "с",
        "while" to "пока",
        "although" to "хотя",
        "because" to "потому что",
        "if" to "если",
        "unless" to "если не",
        "whether" to "ли",
        "before" to "перед",
        "after" to "после",
        "above" to "над",
        "below" to "под",
        "behind" to "позади",
        "beside" to "рядом",
        "beneath" to "под",
        "through" to "сквозь",
        "across" to "через",
        "against" to "против",
        "toward" to "к",
        "upon" to "на",
        "within" to "внутри",
        "without" to "без",
        "along" to "вдоль",
        "around" to "вокруг",
        "among" to "среди",
        "enough" to "достаточно",
        "too" to "тоже",
        "very" to "очень",
        "almost" to "почти",
        "just" to "просто",
        "even" to "даже",
        "still" to "всё ещё",
        "yet" to "ещё",
        "already" to "уже",
        "never" to "никогда",
        "always" to "всегда",
        "sometimes" to "иногда",
        "often" to "часто",
        "rarely" to "редко",
        "usually" to "обычно",
        "once" to "однажды",
        "twice" to "дважды",
        "again" to "снова",
        "then" to "тогда",
        "now" to "сейчас",
        "soon" to "скоро",
        "later" to "позже",
        "early" to "рано",
        "today" to "сегодня",
        "tomorrow" to "завтра",
        "yesterday" to "вчера",
        "tonight" to "сегодня вечером",
        "midnight" to "полночь",
        "dawn" to "рассвет",
        "dusk" to "сумерки",
        "sunset" to "закат",
        "sunrise" to "восход",
        "noon" to "полдень",
        "check" to "проверить",
        "checking" to "проверка",
        "find" to "найти",
        "finding" to "находка",
        "found" to "найденный",
        "need" to "нуждаться",
        "give" to "дать",
        "giving" to "дающий",
        "come" to "приходить",
        "came" to "пришедший",
        "go" to "идти",
        "went" to "шедший",
        "gone" to "шедший",
        "take" to "брать",
        "took" to "взявший",
        "taken" to "взятый",
        "make" to "делать",
        "made" to "сделанный",
        "get" to "получать",
        "got" to "получивший",
        "see" to "видеть",
        "seen" to "виденный",
        "saw" to "видевший",
        "hear" to "слышать",
        "heard" to "слышанный",
        "know" to "знать",
        "known" to "известный",
        "knew" to "знавший",
        "think" to "думать",
        "thought" to "мысль",
        "want" to "хотеть",
        "wanted" to "желаемый",
        "try" to "пытаться",
        "tried" to "попытавшийся",
        "ask" to "спрашивать",
        "asked" to "спросивший",
        "tell" to "рассказывать",
        "told" to "рассказанный",
        "say" to "говорить",
        "said" to "сказанный",
        "speak" to "говорить",
        "spoken" to "говоренный",
        "spoke" to "говоривший",
        "read" to "читать",
        "write" to "писать",
        "written" to "написанный",
        "work" to "работать",
        "live" to "жить",
        "lived" to "проживший",
        "die" to "умирать",
        "died" to "умерший",
        "run" to "бегать",
        "ran" to "бежавший",
        "walk" to "идти",
        "walked" to "шедший",
        "stop" to "останавливаться",
        "stopped" to "остановившийся",
        "start" to "начинать",
        "started" to "начавший",
        "open" to "открывать",
        "opened" to "открывший",
        "close" to "закрывать",
        "closed" to "закрывший",
        "turn" to "поворачивать",
        "turned" to "повернувший",
        "move" to "двигать",
        "moved" to "двигавший",
        "look" to "смотреть",
        "looked" to "смотревший",
        "feel" to "чувствовать",
        "felt" to "чувствовавший",
        "believe" to "верить",
        "believed" to "веривший",
        "remember" to "помнить",
        "remembered" to "помнивший",
        "forget" to "забывать",
        "forgot" to "забывший",
        "forgotten" to "забытый",
        "understand" to "понимать",
        "understood" to "понявший",
        "help" to "помогать",
        "helped" to "помогавший",
        "love" to "любить",
        "loved" to "любивший",
        "hate" to "ненавидеть",
        "hated" to "ненавидевший",
        "wait" to "ждать",
        "waited" to "ждавший",
        "stand" to "стоять",
        "stood" to "стоявший",
        "sit" to "сидеть",
        "sat" to "сидевший",
        "sleep" to "спать",
        "sleap" to "спавший",
        "eat" to "есть",
        "ate" to "евший",
        "eaten" to "съеденный",
        "drink" to "пить",
        "drank" to "пивший",
        "drunk" to "выпивший",
        "wear" to "носить",
        "wore" to "носивший",
        "worn" to "ношенный",
        "buy" to "покупать",
        "bought" to "купивший",
        "sell" to "продавать",
        "sold" to "продавший",
        "pay" to "платить",
        "paid" to "оплативший",
        "play" to "играть",
        "played" to "игравший",
        "win" to "выигрывать",
        "won" to "выигравший",
        "lose" to "проигрывать",
        "lost" to "проигравший",
        "fight" to "сражаться",
        "fought" to "сражавшийся",
        "break" to "ломать",
        "broken" to "сломанный",
        "broke" to "сломавший",
        "build" to "строить",
        "built" to "построенный",
        "create" to "создавать",
        "created" to "созданный",
        "change" to "менять",
        "changed" to "изменивший",
        "become" to "становиться",
        "became" to "ставший",
        "happen" to "случаться",
        "happened" to "случившийся",
        "appear" to "появляться",
        "appeared" to "появившийся",
        "exist" to "существовать",
        "existed" to "существовавший",
        "remain" to "оставаться",
        "remained" to "остававшийся",
        "seem" to "казаться",
        "seemed" to "казавшийся",
        "mean" to "означать",
        "meant" to "означавший",
        "leave" to "покидать",
        "left" to "покинувший",
        "put" to "ставить",
        "placed" to "поставленный",
        "keep" to "хранить",
        "kept" to "хранивший",
        "let" to "позволять",
        "allowed" to "позволенный",
        "begin" to "начинать",
        "begun" to "начатый",
        "began" to "начавший",
        "show" to "показывать",
        "shown" to "показанный",
        "listen" to "слушать",
        "listened" to "слушавший",
        "answer" to "отвечать",
        "answered" to "ответивший",
        "choose" to "выбирать",
        "chosen" to "выбранный",
        "chose" to "выбранный",
        "flee" to "сбежать",
        "fled" to "сбежал",
        "fleeing" to "бегущий",
        "arrest" to "арrestовать",
        "arrested" to "арестован",
        "confess" to "признаться",
        "confessed" to "признался",
        "sentence" to "приговаривать",
        "sentenced" to "приговорён",
        "deny" to "отрицать",
        "denied" to "отклонено",
        "escape" to "сбегать",
        "escaped" to "сбежавший",
        "kill" to "убивать",
        "killing" to "убийство",
        "killed" to "убитый",
        "murder" to "убийство",
        "murdered" to "убитый",
        "murderer" to "убийца",
        "convict" to "осуждать",
        "convicted" to "осуждённый",
        "acquit" to "оправдывать",
        "acquitted" to "оправданный",
        "police" to "полиция",
        "killer" to "убийца",
        "twist" to "поворот",
        "checked" to "проверенный",
        "and" to "и",
        "or" to "или",
        "but" to "но",
        "for" to "для",
        "to" to "к",
        "with" to "с",
        "from" to "от",
        "about" to "о",
        "into" to "в",
        "onto" to "на",
        "weapon" to "оружие",
        "weapons" to "оружие",
        "quest" to "квест",
        "quests" to "квесты",
        "inventory" to "инвентарь",
        "item" to "предмет",
        "items" to "предметы",
        "armor" to "броня",
        "shield" to "щит",
        "helmet" to "шлем",
        "potion" to "зелье",
        "spell" to "заклинание",
        "magic" to "магия",
        "enemy" to "враг",
        "enemies" to "враги",
        "monster" to "монстр",
        "monsters" to "монстры",
        "attack" to "атака",
        "defense" to "защита",
        "damage" to "урон",
        "health" to "здоровье",
        "level" to "уровень",
        "skill" to "навык",
        "skills" to "навыки",
        "reward" to "награда",
        "loot" to "добыча",
        "drop" to "сброс",
        "dungeon" to "подземелье",
        "boss" to "босс",
        "area" to "зона",
        "zone" to "зона",
        "trade" to "торговля",
        "price" to "цена",
        "cost" to "стоимость",
        "craft" to "крафт",
        "crafting" to "крафтинг",
        "repair" to "ремонт",
        "map" to "карта",
        "teleport" to "телепорт",
        "fast" to "быстрый",
        "slow" to "медленный",
        "strong" to "сильный",
        "weak" to "слабый",
        "rare" to "редкий",
        "legendary" to "легендарный",
        "common" to "обычный",
        "epic" to "эпический",
        "quality" to "качество",
        "mission" to "миссия",
        "task" to "задание",
        "goal" to "цель",
        "town" to "город",
        "village" to "деревня",
        "city" to "город",
        "merchant" to "торговец",
        "vendor" to "продавец",
        "banker" to "банкир",
        "guild" to "гильдия",
        "clan" to "клан",
        "party" to "группа",
        "team" to "команда",
        "chat" to "чат",
        "message" to "сообщение",
        "friend" to "друг",
        "server" to "сервер",
        "world" to "мир",
        "realm" to "царство",
        "hp" to "здоровье",
        "mp" to "мана",
        "xp" to "опыт",
        "is" to "является",
        "are" to "являются",
        "am" to "являюсь",
        "was" to "был",
        "were" to "были",
        "been" to "был",
        "has" to "имеет",
        "have" to "иметь",
        "had" to "имел",
        "does" to "делает",
        "do" to "делать",
        "did" to "сделал",
        "more" to "больше",
        "less" to "меньше",
        "most" to "самый",
        "many" to "много",
        "few" to "мало",
        "much" to "много",
        "coins" to "монеты",
        "coin" to "монета",
        "lot" to "много",
        "little" to "мало",
        "what" to "что",
        "who" to "кто",
        "whom" to "кому",
        "which" to "который",
        "whose" to "чей",
        "where" to "где",
        "when" to "когда",
        "why" to "почему",
        "how" to "как",
        "new" to "новый",
        "old" to "старый",
        "big" to "большой",
        "long" to "длинный",
        "short" to "короткий",
        "first" to "первый",
        "last" to "последний",
        "next" to "следующий",
        "good" to "хороший",
        "bad" to "плохой",
        "better" to "лучший",
        "worse" to "хуже",
        "all" to "все",
        "every" to "каждый",
        "each" to "каждый",
        "some" to "некоторые",
        "no" to "нет",
        "not" to "не",
        "nothing" to "ничего",
        "everything" to "всё",
        "something" to "что-то",
        "anything" to "что-нибудь",
        "only" to "только",
        "also" to "тоже",
        "yes" to "да",
        "maybe" to "может быть",
        "perhaps" to "возможно",
        "i" to "я",
        "me" to "мне",
        "my" to "мой",
        "mine" to "мой",
        "us" to "нам",
        "we" to "мы",
        "you" to "ты",
        "he" to "он",
        "him" to "ему",
        "his" to "его",
        "she" to "она",
        "her" to "её",
        "its" to "его",
        "they" to "они",
        "them" to "им",
        "their" to "их",
        "theirs" to "их",
        "a" to "",
        "an" to "",
        "the" to "",
        "in" to "в",
        "on" to "на",
        "at" to "в",
        "by" to "у",
        "of" to "",
        "over" to "над",
        "under" to "под",
    )
}
